### ISSUE TITLE
Contour du choix de couleur de l’espace de travail à améliorer

### ISSUE THREAD

**Issue by Paulin85** [Vision-Data/app#71]
![Image](https://user-images.githubusercontent.com/46808735/198055389-1640ded6-ff25-4007-8e0f-4d2241813154.PNG)

**Comment by LeoneLal** [comment]
![Image](https://user-images.githubusercontent.com/45849538/203515428-621cd02e-85d0-4210-bae2-48f747dddb8b.png)

Ajouter un background : none; sur l'input
